#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".
MAJOR_VERSION="1.0."
MINOR_VERSION=`git rev-list --all | wc -l | sed "s/[ \t]//g"`
echo "$MAJOR_VERSION$MINOR_VERSION" >VERSION
